name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1a

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sashkoklapan/aws_lab_web:latest

      - name: Deploy to AWS EC2 Instance
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@44.211.125.30 'docker pull sashkoklapan/aws_lab_web:latest'
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@44.211.125.30 'docker stop aws_lab_web_1'
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@44.211.125.30 'docker rm aws_lab_web_1'
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@44.211.125.30 'docker run -d -p 80:80 --name aws_lab_web_1 sashkoklapan/aws_lab_web:latest'
