# name: Deploy to AWS

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up AWS CLI
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: AKIARG6QCKANY37TZBIJ
#           aws-secret-access-key: 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
#           aws-region: us-east-1

#       - name: Build and Publish Docker Image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           push: true
#           tags: sashkoklapan/aws_lab_web:latest
#           username: sashkoklapan
#           password: dckr_pat_Nt954C3PriO4N9Xwd_PxaHYVwCM

#       - name: Deploy to AWS EC2 Instance
#         run: |
#           ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@ec2-44-211-125-30.compute-1.amazonaws.com 'docker pull sashkoklapan/aws_lab_web:latest'
#           ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@ec2-44-211-125-30.compute-1.amazonaws.com 'docker stop aws_lab_web_1'
#           ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@ec2-44-211-125-30.compute-1.amazonaws.com 'docker rm aws_lab_web_1'
#           ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@ec2-44-211-125-30.compute-1.amazonaws.com 'docker run -d --name aws_lab_web_1 -p 80:80 sashkoklapan/aws_lab_web:latest'
name: Docker Build and Publish
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sashkoklapan/aws_lab_web:latest

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS EC2 Instance
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@ec2-44-211-125-30.compute-1.amazonaws.com 'docker pull sashkoklapan/aws_lab_web:latest'
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@ec2-44-211-125-30.compute-1.amazonaws.com 'docker stop aws_lab_web_1'
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@ec2-44-211-125-30.compute-1.amazonaws.com 'docker rm aws_lab_web_1'
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@ec2-44-211-125-30.compute-1.amazonaws.com 'docker run -d --name aws_lab_web_1 -p 80:80 sashkoklapan/aws_lab_web:latest'
